# godev configuration file
# Location: ~/.config/godev/config
# 
# This file is auto-generated by godev --setup
# You can edit it manually to customize godev behavior

# ============================================================================
# BASE DIRECTORY
# ============================================================================
# The root directory where all your development projects are located
# godev will scan this directory (one level deep) to find your projects
#
# Examples:
#   GODEV_BASE_DIR="$HOME/dev"                 # Standard location
#   GODEV_BASE_DIR="$HOME/projects"            # Alternative
#   GODEV_BASE_DIR="/Users/john/workspace"     # Absolute path
#   GODEV_BASE_DIR="$HOME/code/personal"       # Specific folder
#
# Tips:
#   - Use absolute paths or $HOME variable
#   - Don't use ~ (it won't expand correctly)
#   - Make sure the directory exists
#   - Projects should be direct children of this directory
GODEV_BASE_DIR="$HOME/dev"

# ============================================================================
# FZF INTEGRATION
# ============================================================================
# Enable/disable FZF (fuzzy finder) integration
# FZF provides a beautiful interactive interface for project selection
#
# Values:
#   "true"  - Enable FZF if installed (recommended)
#   "false" - Use basic numbered list selection
#
# Notes:
#   - This is auto-detected during installation
#   - If FZF is not installed, godev falls back to basic mode automatically
#   - Install FZF for best experience: brew install fzf (macOS)
GODEV_FZF_ENABLED="true"

# ============================================================================
# CACHE TTL (Time To Live)
# ============================================================================
# How long (in seconds) to keep cached project information
# godev caches project listings to improve performance
#
# Recommended values:
#   3600   - 1 hour (default, good for most users)
#   1800   - 30 minutes (if you add/remove projects frequently)
#   7200   - 2 hours (if you have stable project structure)
#   300    - 5 minutes (for rapid development/testing)
#
# Notes:
#   - Shorter TTL = more frequent scans = slower but more up-to-date
#   - Longer TTL = faster listings but might miss recent changes
#   - You can force cache refresh by deleting: ~/.config/godev/cache
#   - Cache includes: git status, branches, commits, activity
GODEV_CACHE_TTL=3600

# ============================================================================
# ADVANCED SETTINGS (Optional - Uncomment to use)
# ============================================================================

# Maximum depth for project scanning
# Default: 1 (only direct children of base directory)
# Increase if you have nested project structures
# Warning: Higher values slow down scanning significantly
# GODEV_MAX_DEPTH=1

# Custom exclusion patterns (space-separated)
# Add patterns to exclude specific directories from scanning
# These are IN ADDITION to built-in exclusions (node_modules, .git, etc.)
# GODEV_EXCLUDE_PATTERNS="temp/* old-* archived-*"

# Color scheme (uncomment to disable colors)
# Useful for terminals that don't support colors well
# GODEV_NO_COLOR="false"

# Default sort order for --list
# Options: name, activity, date, status
# GODEV_DEFAULT_SORT="name"

# Show project path in listings
# If true, shows full path instead of just project name
# GODEV_SHOW_FULL_PATH="false"

# Activity threshold for indicators
# Number of commits in last 30 days for each activity level
# Format: low,medium,high
# Default: 5,20,50
# GODEV_ACTIVITY_THRESHOLDS="5,20,50"

# ============================================================================
# INTEGRATION SETTINGS (Future features)
# ============================================================================

# Editor integration (planned feature)
# Automatically open projects in your preferred editor
# GODEV_EDITOR="code"  # VSCode
# GODEV_EDITOR="nvim"  # Neovim
# GODEV_EDITOR="vim"   # Vim

# Auto-actions on navigation (planned feature)
# Commands to run automatically when entering a project
# GODEV_AUTO_GIT_PULL="false"
# GODEV_AUTO_NPM_INSTALL="false"

# Cloud sync (planned feature)
# Sync project list across multiple machines
# GODEV_CLOUD_SYNC="false"
# GODEV_CLOUD_PROVIDER="github"

# ============================================================================
# NOTES
# ============================================================================
#
# 1. After editing this file, changes take effect immediately
#    No need to restart shell or run godev --setup
#
# 2. To reset to defaults, delete this file and run:
#    godev --setup
#
# 3. Comments (lines starting with #) are ignored
#
# 4. Blank lines are ignored
#
# 5. Values should not have quotes unless they contain spaces
#    Correct: GODEV_BASE_DIR=$HOME/dev
#    Also correct: GODEV_BASE_DIR="$HOME/my projects"
#
# 6. Variables are sourced by the godev script using:
#    source ~/.config/godev/config
#
# 7. You can use shell variables and expansion:
#    GODEV_BASE_DIR="$HOME/dev"           ✓ Good
#    GODEV_BASE_DIR="~/dev"               ✗ Bad (~ won't expand)
#    GODEV_BASE_DIR="/home/$USER/dev"     ✓ Good
#
# ============================================================================
# TROUBLESHOOTING
# ============================================================================
#
# Configuration not working?
#
# 1. Check syntax:
#    source ~/.config/godev/config
#    (should have no errors)
#
# 2. Check permissions:
#    ls -la ~/.config/godev/config
#    (should be readable)
#
# 3. Check base directory exists:
#    ls -la $GODEV_BASE_DIR
#    (should show your projects)
#
# 4. View current config:
#    cat ~/.config/godev/config
#
# 5. Reset to defaults:
#    rm ~/.config/godev/config
#    godev --setup
#
# ============================================================================
# EXAMPLES BY USE CASE
# ============================================================================
#
# Web Developer:
#   GODEV_BASE_DIR="$HOME/web-projects"
#   GODEV_CACHE_TTL=1800
#   GODEV_FZF_ENABLED="true"
#
# DevOps Engineer:
#   GODEV_BASE_DIR="$HOME/infrastructure"
#   GODEV_CACHE_TTL=7200  # Infra changes less frequently
#   GODEV_FZF_ENABLED="true"
#
# Freelancer/Consultant:
#   GODEV_BASE_DIR="$HOME/clients"
#   GODEV_CACHE_TTL=3600
#   GODEV_FZF_ENABLED="true"
#
# Student/Learner:
#   GODEV_BASE_DIR="$HOME/learning"
#   GODEV_CACHE_TTL=1800  # Frequent new projects
#   GODEV_FZF_ENABLED="true"
#
# Open Source Maintainer:
#   GODEV_BASE_DIR="$HOME/opensource"
#   GODEV_CACHE_TTL=3600
#   GODEV_FZF_ENABLED="true"
#
# ============================================================================
# SUPPORT
# ============================================================================
#
# Documentation: https://github.com/YOUR_USER/godev
# Issues: https://github.com/YOUR_USER/godev/issues
# Discussions: https://github.com/YOUR_USER/godev/discussions
#
# ============================================================================
